/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DroneState {
  'status' : string,
  'signalStrength' : bigint,
  'batteryLevel' : bigint,
  'altitude' : number,
  'flightMode' : string,
  'heading' : number,
  'speed' : number,
  'position' : Position,
  'altitudeLimit' : number,
}
export interface LogEntry { 'message' : string, 'timestamp' : bigint }
export interface Position { 'x' : number, 'y' : number, 'z' : number }
export interface _SERVICE {
  'ascend' : ActorMethod<[number], DroneState>,
  'captureSnapshot' : ActorMethod<[], DroneState>,
  'descend' : ActorMethod<[number], DroneState>,
  'emergencyStop' : ActorMethod<[], DroneState>,
  'getDroneState' : ActorMethod<[], DroneState>,
  'getMissionLog' : ActorMethod<[], Array<LogEntry>>,
  'land' : ActorMethod<[], DroneState>,
  'moveBackward' : ActorMethod<[number], DroneState>,
  'moveForward' : ActorMethod<[number], DroneState>,
  'moveLeft' : ActorMethod<[number], DroneState>,
  'moveRight' : ActorMethod<[number], DroneState>,
  'returnToHome' : ActorMethod<[], DroneState>,
  'setAltitudeLimit' : ActorMethod<[number], DroneState>,
  'setFlightMode' : ActorMethod<[string], DroneState>,
  'setSpeed' : ActorMethod<[number], DroneState>,
  'simulateTick' : ActorMethod<[], undefined>,
  'takeoff' : ActorMethod<[], DroneState>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];