/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Position = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const DroneState = IDL.Record({
  'status' : IDL.Text,
  'signalStrength' : IDL.Nat,
  'batteryLevel' : IDL.Nat,
  'altitude' : IDL.Float64,
  'flightMode' : IDL.Text,
  'heading' : IDL.Float64,
  'speed' : IDL.Float64,
  'position' : Position,
  'altitudeLimit' : IDL.Float64,
});
export const LogEntry = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'ascend' : IDL.Func([IDL.Float64], [DroneState], []),
  'captureSnapshot' : IDL.Func([], [DroneState], []),
  'descend' : IDL.Func([IDL.Float64], [DroneState], []),
  'emergencyStop' : IDL.Func([], [DroneState], []),
  'getDroneState' : IDL.Func([], [DroneState], ['query']),
  'getMissionLog' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'land' : IDL.Func([], [DroneState], []),
  'moveBackward' : IDL.Func([IDL.Float64], [DroneState], []),
  'moveForward' : IDL.Func([IDL.Float64], [DroneState], []),
  'moveLeft' : IDL.Func([IDL.Float64], [DroneState], []),
  'moveRight' : IDL.Func([IDL.Float64], [DroneState], []),
  'returnToHome' : IDL.Func([], [DroneState], []),
  'setAltitudeLimit' : IDL.Func([IDL.Float64], [DroneState], []),
  'setFlightMode' : IDL.Func([IDL.Text], [DroneState], []),
  'setSpeed' : IDL.Func([IDL.Float64], [DroneState], []),
  'simulateTick' : IDL.Func([], [], []),
  'takeoff' : IDL.Func([], [DroneState], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Position = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const DroneState = IDL.Record({
    'status' : IDL.Text,
    'signalStrength' : IDL.Nat,
    'batteryLevel' : IDL.Nat,
    'altitude' : IDL.Float64,
    'flightMode' : IDL.Text,
    'heading' : IDL.Float64,
    'speed' : IDL.Float64,
    'position' : Position,
    'altitudeLimit' : IDL.Float64,
  });
  const LogEntry = IDL.Record({ 'message' : IDL.Text, 'timestamp' : IDL.Int });
  
  return IDL.Service({
    'ascend' : IDL.Func([IDL.Float64], [DroneState], []),
    'captureSnapshot' : IDL.Func([], [DroneState], []),
    'descend' : IDL.Func([IDL.Float64], [DroneState], []),
    'emergencyStop' : IDL.Func([], [DroneState], []),
    'getDroneState' : IDL.Func([], [DroneState], ['query']),
    'getMissionLog' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'land' : IDL.Func([], [DroneState], []),
    'moveBackward' : IDL.Func([IDL.Float64], [DroneState], []),
    'moveForward' : IDL.Func([IDL.Float64], [DroneState], []),
    'moveLeft' : IDL.Func([IDL.Float64], [DroneState], []),
    'moveRight' : IDL.Func([IDL.Float64], [DroneState], []),
    'returnToHome' : IDL.Func([], [DroneState], []),
    'setAltitudeLimit' : IDL.Func([IDL.Float64], [DroneState], []),
    'setFlightMode' : IDL.Func([IDL.Text], [DroneState], []),
    'setSpeed' : IDL.Func([IDL.Float64], [DroneState], []),
    'simulateTick' : IDL.Func([], [], []),
    'takeoff' : IDL.Func([], [DroneState], []),
  });
};

export const init = ({ IDL }) => { return []; };