/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LogEntry {
    message: string;
    timestamp: bigint;
}
export interface Position {
    x: number;
    y: number;
    z: number;
}
export interface DroneState {
    status: string;
    signalStrength: bigint;
    batteryLevel: bigint;
    altitude: number;
    flightMode: string;
    heading: number;
    speed: number;
    position: Position;
    altitudeLimit: number;
}
export interface backendInterface {
    ascend(amount: number): Promise<DroneState>;
    captureSnapshot(): Promise<DroneState>;
    descend(amount: number): Promise<DroneState>;
    emergencyStop(): Promise<DroneState>;
    getDroneState(): Promise<DroneState>;
    getMissionLog(): Promise<Array<LogEntry>>;
    land(): Promise<DroneState>;
    moveBackward(distance: number): Promise<DroneState>;
    moveForward(distance: number): Promise<DroneState>;
    moveLeft(distance: number): Promise<DroneState>;
    moveRight(distance: number): Promise<DroneState>;
    returnToHome(): Promise<DroneState>;
    setAltitudeLimit(limit: number): Promise<DroneState>;
    setFlightMode(mode: string): Promise<DroneState>;
    setSpeed(newSpeed: number): Promise<DroneState>;
    simulateTick(): Promise<void>;
    takeoff(): Promise<DroneState>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async ascend(arg0: number): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.ascend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ascend(arg0);
            return result;
        }
    }
    async captureSnapshot(): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.captureSnapshot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.captureSnapshot();
            return result;
        }
    }
    async descend(arg0: number): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.descend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.descend(arg0);
            return result;
        }
    }
    async emergencyStop(): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.emergencyStop();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emergencyStop();
            return result;
        }
    }
    async getDroneState(): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.getDroneState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDroneState();
            return result;
        }
    }
    async getMissionLog(): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMissionLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMissionLog();
            return result;
        }
    }
    async land(): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.land();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.land();
            return result;
        }
    }
    async moveBackward(arg0: number): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.moveBackward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveBackward(arg0);
            return result;
        }
    }
    async moveForward(arg0: number): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.moveForward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveForward(arg0);
            return result;
        }
    }
    async moveLeft(arg0: number): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.moveLeft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveLeft(arg0);
            return result;
        }
    }
    async moveRight(arg0: number): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.moveRight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveRight(arg0);
            return result;
        }
    }
    async returnToHome(): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.returnToHome();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnToHome();
            return result;
        }
    }
    async setAltitudeLimit(arg0: number): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.setAltitudeLimit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAltitudeLimit(arg0);
            return result;
        }
    }
    async setFlightMode(arg0: string): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.setFlightMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFlightMode(arg0);
            return result;
        }
    }
    async setSpeed(arg0: number): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.setSpeed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSpeed(arg0);
            return result;
        }
    }
    async simulateTick(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.simulateTick();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulateTick();
            return result;
        }
    }
    async takeoff(): Promise<DroneState> {
        if (this.processError) {
            try {
                const result = await this.actor.takeoff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.takeoff();
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
